### ISSUE TITLE
the tests seem to be breaking

### ISSUE THREAD

**Issue by pdiniz13** [DeeSnow97/koa-easy-ws#1]
I've tried running the project but I keep getting Uncaught Error: socket hang up

**Comment by b3nsn0w** [comment]
Thanks for the report! Just checked, could not reproduce, so I've added some debug logging to the tests. Could you please try to run `DEBUG=koa-easy-ws:test npm run test` on the latest commit and paste your console output here?

**Comment by pdiniz13** [comment]
@b3nsn0w this is the output from the debug
```
> standard && mocha



  exposed server
  koa-easy-ws:test running test 'exposed' +0ms
    ✓ should be a ws server

  renamed property
  koa-easy-ws:test server started for test 'renamed' +0ms
  koa-easy-ws:test server listening for test 'renamed' +2ms
  koa-easy-ws:test running test 'renamed/sidious' +1ms
    1) should detect 'ctx.sidious' on route '/sidious'
  koa-easy-ws:test running test 'renamed/maul' +9ms
    2) should detect 'ctx.maul' on route '/maul'
  koa-easy-ws:test server closed for test 'renamed' +2ms

  composing with router
  koa-easy-ws:test server started for test 'router' +0ms
  koa-easy-ws:test server listening for test 'router' +0ms
  koa-easy-ws:test running test 'router/obi' +0ms
    3) should connect to handler at '/pow/obi'
  koa-easy-ws:test running test 'router/ani' +2ms
    4) should connect to handler at '/pow/ani'
  koa-easy-ws:test server closed for test 'router' +1ms

  simple example
  koa-easy-ws:test server started for test 'simple' +0ms
  koa-easy-ws:test server listening for test 'simple' +0ms
  koa-easy-ws:test running test 'simple/websocket' +1ms
    5) should reply to websocket
  koa-easy-ws:test running test 'simple/http' +1ms
    ✓ should still handle http
  koa-easy-ws:test server closed for test 'simple' +9ms


  2 passing (44ms)
  5 failing

  1) renamed property
       should detect 'ctx.sidious' on route '/sidious':
     Uncaught Error: socket hang up
      at createHangUpError (_http_client.js:331:15)
      at Socket.socketOnEnd (_http_client.js:423:23)
      at endReadableNT (_stream_readable.js:1064:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)

  2) renamed property
       should detect 'ctx.maul' on route '/maul':
     Uncaught Error: socket hang up
      at createHangUpError (_http_client.js:331:15)
      at Socket.socketOnEnd (_http_client.js:423:23)
      at endReadableNT (_stream_readable.js:1064:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)

  3) composing with router
       should connect to handler at '/pow/obi':
     Uncaught Error: socket hang up
      at createHangUpError (_http_client.js:331:15)
      at Socket.socketOnEnd (_http_client.js:423:23)
      at endReadableNT (_stream_readable.js:1064:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)

  4) composing with router
       should connect to handler at '/pow/ani':
     Uncaught Error: socket hang up
      at createHangUpError (_http_client.js:331:15)
      at Socket.socketOnEnd (_http_client.js:423:23)
      at endReadableNT (_stream_readable.js:1064:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)

  5) simple example
       should reply to websocket:
     Uncaught Error: socket hang up
      at createHangUpError (_http_client.js:331:15)
      at Socket.socketOnEnd (_http_client.js:423:23)
      at endReadableNT (_stream_readable.js:1064:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)



npm ERR! code ELIFECYCLE
npm ERR! errno 5
npm ERR! koa-easy-ws@1.0.6 test: standard && mocha
```

**Comment by pdiniz13** [comment]
I also tried adding some additional console logs to the index file but the upgrade event doesn't seem to be getting called.

**Comment by pdiniz13** [comment]
also what version of node are you using?

**Comment by b3nsn0w** [comment]
I'm currently on node 10.9.0, npm 6.4.1, linux, and the package versions match the package.json. I also think it's something in the environment, how about yours?

**Comment by b3nsn0w** [comment]
Just managed to reproduce the issue on node 8.11.4, log output is same as yours.

**Comment by pdiniz13** [comment]
yup i'm on node 8.11.4. on node 10.9.0 it does work fine for me

**Comment by b3nsn0w** [comment]
Quick update: on node 8 websocket upgrade requests don't seem to reach the Koa middleware at all, currently trying to figure out why.

**Comment by pdiniz13** [comment]
I was actually going to message you that and completely forgot. Nodes .on('upgrade') seems to be handled differently. With node 10 coming into lts next month i'm actually fine with upgrading to it. But if you want to make it work for node 8. I tried quite a few things yesterday trying to see what was wrong with the package, didn't know it was a node version thing, and tried to use the package https://github.com/VanCoding/koa-upgrade to see if I could work around the issue. He built the package a while ago, it was for koa 1 , and he captured the upgrade request in a fairly different setup. I've also only started looking into koa, moving over from express, yesterday so you probably have a better understanding of koa's internal workings and might be able to make better use of it.

**Comment by b3nsn0w** [comment]
Seems like WebSocket upgrade requests aren't handled as simple requests by Node's HTTP module prior to version 10, which means they don't get sent through Koa. I've managed to find a workaround:

```node
const server = http.createServer(app.callback())

if (parseInt(process.versions.node) < 10) { // little bit of trickery here, parseInt stops at the first dot
  server.on('upgrade', req => app.callback()(req, new http.ServerResponse({})))
}

server.listen() // use this instead of app.listen()
```

We're basically injecting the upgrade requests into Koa manually with this technique. The workaround uses a response that's not tied to anything, which does take away your ability to respond as if it was a normal HTTP request, but since the browser expects an upgrade and not an HTTP response this shouldn't happen in practice anyway.

I'm working on a more permanent fix, but for now this seems to clear the tests and not throw any errors in case the route isn't handled. Let me know if it causes any problems in practice for you.

**Comment by b3nsn0w** [comment]
Just saw your comment from an hour ago (didn't load for some reason), that's great stuff. Actually, my motivation was the same, and even managed to do sort of the same thing with the workaround. Thanks for the link.

**Comment by pdiniz13** [comment]
yup that does seem to solve it

**Comment by b3nsn0w** [comment]
Workaround added to the package itself. FYI, even though this is a minor version upgrade, it will break the manual workaround on node 8, so you'll need to do either of these two things:

1. Disable the app's workaround. This one is easy, just add an option to the middleware:

    ```javascript
    app.use(websocket('ws', {noServerWorkaround: true}))
    ```

    Everything will continue as it did before the update, you will still need your manual workaround in this case. If you'd like to remove that, option 2 is there:

2. Use the provided workaround. You will need to pass your HTTP server to the middleware.

    ```javascript
    const server = http.createServer(app.callback())

    app.use(websocket('ws', server))

    server.listen()
    ```

More details [here](https://github.com/b3nsn0w/koa-easy-ws/blob/c7250528578d4c5b19dac2a632215407bb858161/README.md#special-usage-for-node-9-or-earlier).
