### ISSUE TITLE
Every connection gets closed by ERR_HTTP_REQUEST_TIMEOUT after a minute

### ISSUE THREAD

**Issue by Mwni** [DeeSnow97/koa-easy-ws#36]
It appears that an upgraded connection is still considered as an ongoing http request, which then gets killed after the default timeout.

```
 Error [ERR_HTTP_REQUEST_TIMEOUT]: Request timeout
      at new NodeError (node:internal/errors:377:5)
      at onRequestTimeout (node:_http_server:706:30)
      at Server.checkConnections (node:_http_server:519:7)
      at listOnTimeout (node:internal/timers:564:17)
      at process.processTimers (node:internal/timers:507:7)
```

**Comment by gchallen** [comment]
I was bit by the same bug, which looks like it came in with [Node 18](https://github.com/nodejs/node/issues/44228). What worked for me is disabling the server `requestTimeout` and `headersTimeout` by setting them to 0:

```typescript
const server = app.listen(PORT)
server.requestTimeout = 0
server.headersTimeout = 0
```

However, this is probably safest if your app is deployed behind a proxy that can close down partial requests properly and prevent against associated DoS attacks.

**Comment by Mwni** [comment]
Yeah this is a bug in Node's C++ socket implementation. This is another workaround:
```js
koa.use(async (ctx, next) => {
	if(ctx.ws){
		ctx.req.socket.ignoreTimeout = true
		//handle socket
	}else{
		return await next(ctx)
	}
})

koa.listen(80)
	.on('clientError', (error, socket) => {
		if(error.code === 'ERR_HTTP_REQUEST_TIMEOUT' && socket.ignoreTimeout)
			return

		console.warn(`client error:`, error)
		socket.destroy()
	})
	
```

**Comment by AaronFriel** [comment]
Thanks for this pointer @Mwni, I've cited this thread in a PR I made as a contribution to add a feature like this library does for Next.js. Your comment gave me the pointer I needed to write this commit: 

https://github.com/vercel/next.js/pull/58704/commits/486b36237a213ebf4c19a3bd8f296fad5b400a64
