### ISSUE TITLE
Property 'server' does not exist on type 'Middleware<ParameterizedContext<{}, WebSocketContext<"ws">>>'.

### ISSUE THREAD

**Issue by sduduzog** [DeeSnow97/koa-easy-ws#9]
I got this error when trying to do the following
```typescript
const websocketMiddleware = websocket()
const websocketServer = websocketMiddleware.server
```

**Comment by b3nsn0w** [comment]
Yeah, that's going to be a typings issue, `websocketMiddleware` in this example is defined as `Middleware<{}, WebSocketContext<PropertyName>>`, which doesn't include the `WebSocketServer` (guessing) on the `server` property. Thanks for the bug report, I'm investigating this one. The solution is definitely to add the prop to the definition, but I don't code TS myself, no clue yet how to add this one.

**Comment by sduduzog** [comment]
This is how I got around it in the meantime
```typescript
const { server } = (websocketMiddleware as unknown) as { server: Server };
```

**Comment by b3nsn0w** [comment]
Thanks a lot for the pull request! You should be able to install version 1.2.1 on npm, your fix is included in it.
